name: exercise
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.0-210.3.beta <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.6
 
flutter_native_splash:
  color: "#8DDBF8"
  image: assets/images/university.png
  android: true
  ios: true
  web: false

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/


